# environment.yml for Skim2Struct
name: skim2struct
channels:
  - bioconda
  - conda-forge

dependencies:
  - python=3.12
  - iqtree
  - hyphy=2.5.71 
  - fpocket
  - autodock-vina
  - openbabel
  - pip
  - pip:
      - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
      - biopython
      - matplotlib
      - seaborn
      - pandas
      - numpy
      - requests
      - psutil
